[[sites]]
url = "https://en.wikipedia.org/wiki/T%C3%BCbingen"
max_pages = 1000
request_delay = 0.5

[[sites]]
url = "https://en.wikipedia.org/wiki/T%C3%BCbingen"
max_pages = 1000
request_delay = 0.3

[[sites]]
url = "https://en.wikivoyage.org/wiki/T%C3%BCbingen"
max_pages = 1000
request_delay = 0.3

[[sites]]
url = "https://uni-tuebingen.de/en/"
max_pages = 1000
request_delay = 0.5

[[sites]]
url = "https://www.tuebingen.de/en/"
max_pages = 1000
request_delay = 0.5

[[sites]]
url = "https://www.tuebingen-info.de/en"
max_pages = 1000
request_delay = 0.5

[[sites]]
url = "https://tuebingenresearchcampus.com/en/"
max_pages = 1000
request_delay = 0.5

[[sites]]
url = "https://cyber-valley.de/en"
max_pages = 1000
request_delay = 0.5

[[sites]]
url = "https://is.mpg.de/"
max_pages = 1000
request_delay = 0.5
